apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-management-api
  template:
    metadata:
      labels:
        app: task-management-api
    spec:
      containers:
      - name: task-management-api
        image: ghcr.io/jannegpriv/task-management:latest  # Will be patched by overlay
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: task-management-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
