apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: janneg

resources:
  - ../../base

patches:
  - path: ingress.yaml
    target:
      kind: Ingress
      name: task-management-ingress

images:
  - name: ghcr.io/jannegpriv/task-management
    newTag: latest
  - name: ghcr.io/jannegpriv/task-management-ui
    newTag: latest
