apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-management
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/jannegpriv/task-management:latest,ghcr.io/jannegpriv/task-management-ui:latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/jannegpriv/task-management-k8s.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
