apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-management-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jannegpriv/task-management-k8s.git'
    path: overlays/production
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: janneg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-management-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jannegpriv/task-management.git'
    path: .
    targetRevision: HEAD
    plugin:
      name: dockerfile-build
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: janneg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-management-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jannegpriv/task-management-ui.git'
    path: .
    targetRevision: HEAD
    plugin:
      name: dockerfile-build
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: janneg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
