apiVersion: v1
kind: ConfigMap
metadata:
  name: dockerfile-build-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: dockerfile-build
    spec:
      version: v1.0
      generate:
        command: ["/bin/sh", "-c"]
        args:
          - |
            if [ -f Dockerfile ]; then
              IMAGE_NAME=$(basename $REPO_URL .git)
              docker build -t $IMAGE_NAME .
              docker tag $IMAGE_NAME jannegpriv/$IMAGE_NAME:latest
              docker push jannegpriv/$IMAGE_NAME:latest
            fi
