apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: janneg
type: Opaque
data:
  # These values should be base64 encoded in the production overlay
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  POSTGRES_DB: dGFza21hbmFnZW1lbnQ=  # taskmanagement
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: janneg
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzL3Rhc2ttYW5hZ2VtZW50  # postgresql://postgres:postgres@postgres/taskmanagement
