apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: janneg
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvdGFza21hbmFnZW1lbnQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: janneg
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvdGFza21hbmFnZW1lbnQ=
