apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: janneg
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: janneg
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-secret-manager
  namespace: janneg
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: janneg
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
