apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 10-sealed-secrets.yaml
  - 15-registry-secret.yaml
  - 20-storage.yaml
  - 30-postgres.yaml
  - 40-backend.yaml
  - 50-frontend.yaml
  - 60-ingress.yaml
