name: Deploy Secrets

on:
  push:
    branches:
      - main
    paths:
      - 'overlays/production/secrets.yaml'
  workflow_dispatch:

jobs:
  deploy-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Deploy Secrets
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # Create a temporary file with the secrets
          cat << EOF > temp-secrets.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: postgres-secrets
            namespace: janneg
          type: Opaque
          data:
            DATABASE_URL: $(echo -n "$DATABASE_URL" | base64)
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: api-secrets
            namespace: janneg
          type: Opaque
          data:
            DATABASE_URL: $(echo -n "$DATABASE_URL" | base64)
          EOF
          
          # Apply the secrets
          kubectl apply -f temp-secrets.yaml
          
          # Clean up
          rm temp-secrets.yaml
